include theme.conf
include effects.conf

font_family      SFMono Nerd Font
bold_font        SFMono Nerd Font Bold
italic_font      SFMono Nerd Font Italic
bold_italic_font SFMono Nerd Font Bold Italic
font_size        11.0
