foreground #d8d8d8
background #1a1a1a
selection_foreground #1a1a1a
selection_background #6b6b6b
cursor #d8d8d8
cursor_text_color #1a1a1a

color0 #2a2a2a
color8 #6b6b6b

color1 #999999
color9 #ababab

color2 #a8a8a8
color10 #bcbcbc

color3 #b8b8b8
color11 #cccccc

color4 #888888
color12 #9c9c9c

color5 #9e9e9e
color13 #b2b2b2

color6 #ababab
color14 #bfbfbf

color7 #cfcfcf
color15 #f2f2f2
