background            #1a1a1a
foreground             #e2e2e2
cursor                  #bebebe
cursor_text_color      #1a1a1a

selection_background    #5b5b5b
selection_foreground    #e2e2e2

url_color               #bebebe

active_border_color     #bebebe
inactive_border_color   #232323
bell_border_color       #8c8c8c

active_tab_background   #232323
active_tab_foreground   #e2e2e2
inactive_tab_background #1a1a1a
inactive_tab_foreground #a5a5a5
tab_bar_background      #1a1a1a

mark1_foreground #1a1a1a
mark1_background #bebebe

color0  #1a1a1a
color8  #444444
color1  #5b5b5b
color9  #8c8c8c
color2  #8a8a8a
color10 #aeaeae
color3  #929292
color11 #aeaeae
color4  #8f8f8f
color12 #aeaeae
color5  #bebebe
color13 #dadada
color6  #939393
color14 #b6b6b6
color7  #a5a5a5
color15 #e2e2e2
